language: python

python:
  - "3.6"

cache: pip
install: 
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov

script: 
  - pytest -v --cov app --cov-report term-missing
  - coverage report
  
after_success:
  - codecov
  - coveralls