language: python

python:
  - "3.6"

env:
  global:
    - CC_TEST_REPOTER_ID=cfde1fbf7e44a03aee53c15df2f06dca720885de3eefb7e0a514d9a59270341b

cache: pip
install: 
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov

before_script: # code coverage tool
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: 
  - pytest -v --cov app --cov-report term-missing
  - coverage report
  
after_success:
  - codecov
  - coveralls